DROP TABLE IF EXISTS roles;

DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS locations;

DROP TABLE IF EXISTS categories;

DROP TABLE IF EXISTS items;

DROP TABLE IF EXISTS orders;

DROP TABLE IF EXISTS transfer_orders;

DROP TABLE IF EXISTS order_carts;