basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: mordekhaigerinlumangkun@gmail.com
    name: Mordekhai Gerin
  description: Inventory Management System.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Cozy Warehouse API
  version: "1.0"
paths: {}
swagger: "2.0"
